export default {
  uploads: "/uploads",
  authors: {
    _params: { id: ":id" },
    root: "/authors",
    get: "/",
    post: "/",
    getById: "/:id",
    put: "/:id",
    delete: "/:id",
  },
  books: {
    _params: { id: ":id", authorId: ":authorId" },
    root: "/books",
    get: "/",
    post: "/",
    getById: "/:id",
    getByAuthorId: "/author/:authorId",
    put: "/:id",
    delete: "/:id",
  },
  users: {
    _params: { id: ":id" },
    root: "/users",
    self: "/self",
    userLogout: "/logout",
    userLogin: "/login",
    userRegister: "/register",
    put: "/:id",
    theme: "/theme/:id",
    language: "/language/:id",
    delete: "/:id",
  },
  stats: {
    _params: { bookId: ":bookId", userId: ":userId" },
    root: "/stats",
    getBookStats: "/:bookId",
    getBookByUserStats: "/:bookId/:userId",
    post: "/",
  },
} as const;
